#!/bin/sh
set -eu
LANGUAGE=java
PROJECT=$1
MODULE=$2
CONFIG_DIR="$HOME/${XDG_CONFIG_HOME+.config}/brix"
CONFIG_PROJECT_DIR="$CONFIG_DIR/$LANGUAGE/project"
CONFIG_MODULE_DIR="$CONFIG_DIR/$LANGUAGE/module"
TLD="com.xenoterracide"

to_java_package() {
  echo "$1" | sed 's/[[:punct:]]/\./g'
}

to_java_package_path() {
  to_java_package "$1" | sed 's/\./\//g'
}

package_dir() {
  echo "java/$(to_java_package_path $TLD)/$(to_java_package_path "$PROJECT")/$(to_java_package_path "$MODULE")"
}

pwd
install -d "$CONFIG_PROJECT_DIR/shared" "$PROJECT"
install -D "$CONFIG_DIR/.editorconfig" "$PROJECT"
install -D "$CONFIG_DIR/.gitattributes" "$PROJECT"
install -D "$CONFIG_DIR/.prettierrc.yml" "$PROJECT"
install -D "$CONFIG_DIR/.lintstagedrc.yml" "$PROJECT"
install -D "$CONFIG_DIR/git-conventional-commits.yaml" "$PROJECT"

sed -i "s/TLD/$TLD/g" "$PROJECT/settings.gradle.kts"
sed -i "s/PROJECT/$PROJECT/g" "$PROJECT/package.json"

MODULE_DIR="$PROJECT/module/$MODULE"
install -D "$CONFIG_MODULE_DIR/build.gradle.kts" "$MODULE_DIR"
sed -i "s/TLD/$TLD/g" "$MODULE_DIR/build.gradle.kts"

install -D "$CONFIG_MODULE_DIR/module-info.java" "$MODULE_DIR/src/main/$(package_dir)"
sed -i "s/TLD.PROJECT.MODULE/$(to_java_package "$TLD.$PROJECT.$MODULE")/g" "$MODULE_DIR/src/main/$(package_dir)/module-info.java"

install -TD "$CONFIG_MODULE_DIR/Application.java" "$MODULE_DIR/src/main/$(package_dir)"
sed -i "s/TLD.PROJECT.MODULE/$(to_java_package "$TLD.$PROJECT.$MODULE")/g" "$MODULE_DIR/src/main/$(package_dir)/Application.java"

cd "$PROJECT"
npm install
./gradlew dependencies --write-locks

git add .
./gradlew spotlessApply
git add -u
git commit -m "chore: initial commit"
set +eu
